version: '3.7'
services:
  node-red:
    restart: unless-stopped
    user: "root"
    ports:
      - "1880:1880"
    volumes:
      - "${TTN_DASHBOARD_DATA}node-red:/data"
    # nodered opens ports on influxdb so it needs to be able to talk to it.
    links:
      - influxdb
    environment:
      TZ: "${TTN_DASHBOARD_TIMEZONE:-GMT}"
    build:
     context: ./node-red
     args:
      NODERED_INSTALL_PLUGINS: "${TTN_DASHBOARD_NODERED_INSTALL_PLUGINS:-}"

  influxdb:
    restart: unless-stopped
    image: influxdb:latest
    volumes:
      - "${TTN_DASHBOARD_DATA}influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: "${TTN_DASHBOARD_INFLUXDB_INITIAL_DATABASE_NAME:-demo}"
      INFLUXDB_INIT_PWD: "${TTN_DASHBOARD_INFLUXDB_ADMIN_PASSWORD:-!notset}"
      INFLUXDB_BIND_ADDRESS: "influxdb:8088"

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    user: "root"
    ports:
      - "3000:3000"
    volumes:
      - "${TTN_DASHBOARD_DATA}grafana:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${TTN_DASHBOARD_GRAFANA_ADMIN_PASSWORD:-!notset}"
      GF_LOG_MODE: "${TTN_DASHBOARD_GRAFANA_LOG_MODE:-console,file}"
      GF_LOG_LEVEL: "${TTN_DASHBOARD_GRAFANA_LOG_LEVEL:-info}"
      GF_INSTALL_PLUGINS: "${TTN_DASHBOARD_GRAFANA_INSTALL_PLUGINS:-}"
      GF_USERS_ALLOW_SIGN_UP: "${TTN_DASHBOARD_GRAFANA_USERS_ALLOW_SIGN_UP:-false}"
    # grafana opens ports on influxdb and postfix, so it needs to be able to talk to it.
    links:
      - influxdb

### end of file ###
